export default [
'AGG Kale bags',
'AGG Salad bags',
'AGG Spinach bags',
'AGG Supergreens bags',
'Apple Bag Fuji',
'Apple Bag Gala',
'Apple Bag Pink',
'Apple Fuji',
'Apple Gala',
'Apple Golden',
'Apple Granny',
'Apple Pink',
'Artichoke',
'Aspargus Loose',
'Avocado',
'Banana',
'Beans',
'Beet Bunch',
'Beetroot',
'Blackberries',
'Blueberries',
'Broccoli',
'Broccolini',
'Brussel',
'Cabbage Green',
'Cabbage Red',
'Capsicum Green',
'Capsicum Red',
'Carrot',
'Carrot Dutch',
'Carrot Purple',
'Carrot Yellow',
'Cauli',
'Celeriac',
'Celery',
'Cherries',
'Chillies Green',
'Chillies Red',
'Coconut',
'Coolabah Rocket 1.5kg',
'Coolabah Roquette punnets',
'Coolabah Salad 1.5kg',
'Coolabah Salad punnets',
'Coolabah Spinach 1.5kg',
'Coolabah Spinach punnets',
'Corn',
'Cucumber Lebanese',
'Daikon',
'Dates',
'Dragonfruit',
'EcoLeaf Kale',
'EcoLeaf Roquette',
'EcoLeaf Spinach',
'Eggplant',
'Eggplant Lebanese',
'Feijoa',
'Fennel',
'Garlic',
'Ginger',
'Grapefruit Ruby',
'Grapefruit Yellow',
'Grapes Green',
'Grapes Red',
'Herb Basil',
'Herb Coriander',
'Herb Dill',
'Herb Parsley',
'Herb Rosemary',
'Herb Sage',
'Honeydew',
'Kale Black',
'Kale Curly',
'Kiwi',
'Leek',
'Lemons',
'Lettuce Cos',
'Lettuce Iceberg',
'Limes',
'Mandy',
'Mandy Net',
'Mango',
'Mushroom Brown',
'Mushroom Punnet',
'Mushroom White',
'Onion Brown',
'Onion Red',
'Orange Nets',
'Oranges',
'Pak Choy',
'Parsnip',
'Passionfruit',
'Paw paw',
'Peaches White',
'Peaches Yellow',
'Pears',
'Persimmon',
'Pineapple',
'Plums',
'Pomegranate',
'Potato Dutch',
'Potato Kestral',
'Potato King Edward',
'Potato Midnight',
'Potato Nicola',
'Potato Ottway',
'Potato Pontiac',
'Potato Sebago',
'Pumpkin',
'Radish',
'Rainbow Chard',
'Raspberries',
'Rhubarb',
'Rockmelon',
'Silverbeet',
'Snow Peas',
'Spinach Bunch',
'Spring Onion',
'Sprouts Mung',
'Sprouts Pea',
'Sprouts Salad',
'Sprouts Sunflower',
'Sprouts Wasabi',
'Stirfry Mix',
'Strawberries',
'Swede',
'Sweet Potato',
'Tangelo',
'Tomatoes',
'Tomatoes Cherry',
'Tomatoes Cherry Roma',
'Tomatoes Roma',
'Tomatoes Truss',
'Tumeric',
'Turnip',
'Watermelon',
'Yellow Squash',
'Zucchini'
]